version: '3.3'

services:
  db:
    container_name: db_bot
    image: postgres:latest
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: tgbot
      #build:
      #context: ./
    image: ilyakhakhalkin/sprachbot_alchemycore:v1.3
    restart: always
    command: >
      bash -c "python3 tgbot.py"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
